# -*- coding: utf-8 -*-
"""FIX.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1P7zkj4WhStwcwUMmZWuQvBWaBHepmMnc
"""

# ==============================
# 1. IMPORT LIBRARY
# ==============================

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

from sklearn.tree import DecisionTreeClassifier, plot_tree
from sklearn.metrics import classification_report, confusion_matrix, accuracy_score
from sklearn.model_selection import StratifiedKFold, cross_val_score, cross_val_predict

# ==============================
# 2. LOAD DATASET
# ==============================

df = pd.read_csv('Data Hipertensi.csv', sep=';')

# header fix
df.columns = df.iloc[0]
df = df[1:].reset_index(drop=True)
df.columns = df.columns.str.strip()

print("Daftar Kolom:")
print(df.columns.tolist())

print("\nShape awal:")
print(df.shape)

# ==============================
# 3. DATA CLEANING
# ==============================

# Umur
df['Umur Tahun'] = df['Umur Tahun'].astype(str)
df['Umur Tahun'] = df['Umur Tahun'].str.replace(' Tahun', '', regex=False)
df['Umur Tahun'] = pd.to_numeric(df['Umur Tahun'], errors='coerce')

# IMT
df['IMT'] = df['IMT'].astype(str)
df['IMT'] = df['IMT'].str.replace(',', '.', regex=False)
df['IMT'] = pd.to_numeric(df['IMT'], errors='coerce')

# Lingkar Perut
df['Lingkar Perut'] = df['Lingkar Perut'].astype(str)
df['Lingkar Perut'] = df['Lingkar Perut'].str.replace(' cm', '', regex=False)
df['Lingkar Perut'] = pd.to_numeric(df['Lingkar Perut'], errors='coerce')

# Sistole
df['Sistole'] = df['Sistole'].astype(str)
df['Sistole'] = df['Sistole'].str.replace(' mm', '', regex=False)
df['Sistole'] = pd.to_numeric(df['Sistole'], errors='coerce')

# Diastole
df['Diastole'] = df['Diastole'].astype(str)
df['Diastole'] = df['Diastole'].str.replace(' Hg', '', regex=False)
df['Diastole'] = pd.to_numeric(df['Diastole'], errors='coerce')

# ==============================
# 4. DROP INVALID
# ==============================

df = df.dropna(subset=[
    'Umur Tahun',
    'IMT',
    'Lingkar Perut',
    'Sistole',
    'Diastole',
    'Merokok',
    'Konsumsi Alkohol',
    'Kurang Sayur/Buah'
])

print("\nShape setelah cleaning:")
print(df.shape)

# ==============================
# 5. ENCODING
# ==============================

df['Merokok'] = df['Merokok'].astype(str).str.strip().str.lower()
df['Konsumsi Alkohol'] = df['Konsumsi Alkohol'].astype(str).str.strip().str.lower()
df['Kurang Sayur/Buah'] = df['Kurang Sayur/Buah'].astype(str).str.strip().str.lower()

df['Merokok'] = df['Merokok'].map({
    'ya': 1,
    'tidak': 0
})

df['Konsumsi Alkohol'] = df['Konsumsi Alkohol'].map({
    'ya': 1,
    'tidak': 0
})

df['Kurang Sayur/Buah'] = df['Kurang Sayur/Buah'].map({
    'ya': 1,
    'tidak': 0
})

df = df.dropna(subset=[
    'Merokok',
    'Konsumsi Alkohol',
    'Kurang Sayur/Buah'
])

# ==============================
# 6. LABEL TARGET
# ==============================

def label_hipertensi(row):
    if row['Sistole'] >= 140 or row['Diastole'] >= 90:
        return 1
    return 0

df['Target'] = df.apply(label_hipertensi, axis=1)

print("\nDistribusi target:")
print(df['Target'].value_counts())

# ==============================
# 7. FEATURE SELECTION
# ==============================

X = df[
    [
        'Umur Tahun',
        'Merokok',
        'Konsumsi Alkohol',
        'Kurang Sayur/Buah',
        'IMT',
        'Lingkar Perut'
    ]
]

y = df['Target']

# ==============================
# 8. BUILD MODEL CART
# ==============================

model = DecisionTreeClassifier(
    criterion='gini',
    max_depth=5,
    min_samples_split=10,
    min_samples_leaf=5,
    random_state=42
)

# ==============================
# 9. CROSS VALIDATION
# ==============================

cv = StratifiedKFold(
    n_splits=5,
    shuffle=True,
    random_state=42
)

scores = cross_val_score(
    model,
    X,
    y,
    cv=cv,
    scoring='accuracy'
)

print("\nAccuracy tiap fold:")
print(scores)

print("\nRata-rata accuracy:")
print(scores.mean())

# ==============================
# 10. PREDIKSI CROSS VALIDATION
# ==============================

y_pred = cross_val_predict(
    model,
    X,
    y,
    cv=cv
)

# ==============================
# 11. EVALUASI
# ==============================

cm = confusion_matrix(y, y_pred)

print("\nConfusion Matrix:")
print(cm)

print("\nClassification Report:")
print(classification_report(y, y_pred))

# ==============================
# 12. TRAIN FINAL MODEL
# ==============================

model.fit(X, y)

# ==============================
# 13. VISUALISASI TREE
# ==============================

plt.figure(figsize=(24, 12))

plot_tree(
    model,
    feature_names=X.columns,
    class_names=['Normal', 'Hipertensi'],
    filled=True,
    rounded=True,
    fontsize=8
)

plt.show()

# ==============================
# 14. FEATURE IMPORTANCE
# ==============================

importance = pd.DataFrame({
    'Feature': X.columns,
    'Importance': model.feature_importances_
})

importance = importance.sort_values(
    by='Importance',
    ascending=False
)

print("\nFeature Importance:")
print(importance)